services:
  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    restart: always
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=file:/app/prisma/dev.db
      - SEED_DB_ON_STARTUP=true
    volumes:
      - todolist_data:/app/prisma

volumes:
  todolist_data:
    driver: local
